### ISSUE TITLE
form_tag syntax

### ISSUE THREAD

**Issue by BrittanyTinnin** [learn-co-curriculum/rails-form_for-on-edit-readme#11]
under Implementation of form_for it shows a method in the form_tag syntax, but in the previous lab for the rails form_tag doesn't show or walk through a method

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
