### ISSUE TITLE
frequent issues with forking and cloning labs 

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/rails-form_for-on-edit-readme#12]
I used to be in the in-person bootcamp, and then got into the online one. But I was gone from the course for a long time. Now that I've started back up again, I have some problems with forking and cloning labs that seem to stem from that transfer. 

This leads to frequent and time-consuming conversations with tech coaches outside of the actual coding for the labs, but just to get the lab open and the tests working. The coaches are skillful and always eventually figure it out, but I'm opening an issue as it seems to be rooted in an ongoing problem. I also can't stay for the Ask A Question session which is currently ongoing. 

When I click the github button to fork down labs, it doesn't get them from learn-co account which issues the v-000 suffix in the url, like in this one: 
https://github.com/learn-co-students/rails-form_for-on-edit-readme-v-000

Instead, mine look like this: 
https://github.com/ode-to-the-code/strong-params-basics-web-051517

And when I use that button, the labs seem to fork from a different source altogether than the learn account:
ode-to-the-code/strong-params-basics-web-051517
forked from procchio6/strong-params-basics-web-051517

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to or a problem with the Learn platform.
Our product team can help you with this. You can reach them at support@learn.co. It's possible you have not been given access to the correct batch for the cohort you're in.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
