### ISSUE TITLE
Forbidden attributes error with params.require

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/rails-form_for-on-edit-readme#13]
Using `@post.update(params.require(:post))` as instructed in the Readme results in a forbidden attributes error. To get the tests to pass, it's necessary to use `@post.update(title: params[:post][:title], description: params[:post][:description])` instead.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
