### ISSUE TITLE
There should be an explaination of the difference in def new in the controller

### ISSUE THREAD

**Issue by Mera-Stackhouse** [learn-co-curriculum/rails-form_for-on-edit-readme#15]
In the controller for form_for, the #new method needs to have a new object that it can pass to the form. But they never mention this. So maybe explain that in here? Or in the next lab, which is an overview of forms.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
