### ISSUE TITLE
Reorder lesson

### ISSUE THREAD

**Issue by gac2117** [learn-co-curriculum/rails-form_for-on-edit-readme#16]
This README would've been helpful if it were before the previous lab "Edit/Update Action".
In that previous lab, it suddenly used `form_for` without explaining it, and now it is being explained in this later lesson.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
