### ISSUE TITLE
Terrible ordering of labs. 

### ISSUE THREAD

**Issue by Dwake5** [learn-co-curriculum/rails-form_for-on-edit-readme#17]
The bad ordering of the labs has really hindered my learning. You've had us building things with all of the routes and then put us through tutorials of each of the singular routes on there own. 

Had us using form_for before the readme on form_for. Just all around its been ordered terrible. Please review the ordering of these labs for future students. It would have saved me a lot of wasted time, stress and effort.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
