### ISSUE TITLE
readme says add patch but not other paths

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/rails-form_for-on-edit-readme#18]
readme told to put patch 'posts/:id', to: 'posts#update' 

but lab doesn't default with index show new create and edit paths

had to add resources :posts, only: [:index, :show, :new, :create, :edit, :update]

minor, but still tangible

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
